### ISSUE TITLE
HomeAssistant Bluetooth proxy

### ISSUE THREAD

**Issue by Fidelity88** [wimaha/TeslaBleHttpProxy#1]
I'm already using HomeAssistant with a Bluetooth proxy. Using this, I can see BLE (only) devices as instructed here:
https://smarthomecircle.com/connect-bluetooth-devices-to-home-assistant-with-bluetooth-proxy

Is there a way I could make the TeslaBleHttpProxy work together with this existing Bluetooth Proxy?

**Comment by wimaha** [comment]
Hello, I have no experience with HomeAssistant. According to the documentation, however, services can be integrated as HTTP requests. You are welcome to create such a solution and submit it as a PR in the README.
