### ISSUE TITLE
vehicle soc: outdated - TeslaMate

### ISSUE THREAD

**Issue by CrazyMgix** [wimaha/TeslaBleHttpProxy#10]
I always get the error that the Soc is outdated. 

DEBUG 2024/06/22 14:49:50 charger status: C
[lp-1 ] WARN 2024/06/22 14:49:50 vehicle soc: outdated (ignored by estimator)
[lp-1 ] DEBUG 2024/06/22 14:49:50 soc estimated: 71.92% (vehicle: 71.00%)
[lp-1 ] DEBUG 2024/06/22 14:49:50 vehicle soc: 72%
[lp-1 ] ERROR 2024/06/22 14:49:50 vehicle soc limit: outdated
[lp-1 ] ERROR 2024/06/22 14:49:50 vehicle range: outdated

This is my configuration:

type: custom
title: Inf
capacity: 78
name: Infinus
chargeenable:
source: http
uri: "http://192.168.178.162:8080/api/1/vehicles/****>
method: POST
body: ""
maxcurrent: # set charger max current (A)
source: http
uri: http://192.168.178.162:8080/api/1/vehicles/****>
method: POST
body: '{"charging_amps": "{{.maxcurrent}}"}'
wakeup: # vehicle wake up command
source: http
uri: http://192.168.178.162:8080/api/1/vehicles/****>
method: POST
body: ""
soc:
source: mqtt
topic: teslamate/cars/1/battery_level
timeout: 60s
range:
source: mqtt
topic: teslamate/cars/1/est_battery_range_km
timeout: 60s
status:
source: combined
plugged:
source: mqtt
topic: teslamate/cars/1/plugged_in
timeout: 60s
charging:
source: mqtt
topic: teslamate/cars/1/charging_state
timeout: 60s
odometer:
source: mqtt
topic: teslamate/cars/1/odometer
timeout: 60s
climater:
source: mqtt
topic: teslamate/cars/1/is_climate_on
timeout: 60s
limitsoc:
source: mqtt
topic: teslamate/cars/1/charge_limit_soc
timeout: 60s

mqtt:
broker: 192.168.178.161:1883

Why does the error message appear?

**Comment by wimaha** [comment]
I think the question is correctly answered by @litithio. Furthermore this is an error log from evcc and not issue related to this repository.
