### ISSUE TITLE
No NFC confirmation request

### ISSUE THREAD

**Issue by faxioman** [wimaha/TeslaBleHttpProxy#34]
Hi,
I'm trying to associate my Model 3 2024:

```
2024/07/20 18:45:23 INFO Key-Request connection established
2024/07/20 18:45:23 INFO sending command=add-key-request body=map[]
2024/07/20 18:45:23 INFO Sent add-key request to LRW3*************8. Confirm by tapping NFC card on center console.
2024/07/20 18:45:23 INFO successfully executed command=add-key-request body=map[]
```

But nothing happens in my car.
I'm using a Mac Book pro with bluetooth connected to my car.
I'm sure I'm missing something... 😅

**Comment by wimaha** [comment]
What happens when you confirm by tapping NFC card on center console?

**Comment by faxioman** [comment]
The problem is that no confirmation request appears on my car

**Comment by wimaha** [comment]
This is expected behavior! You have to confirm by tapping NFC card on center console. Then a message will appear on screen.

**Comment by faxioman** [comment]
I'll try ... now! 😉

**Comment by faxioman** [comment]
Ok, now I can see the key!! Thanks!
At this moment, all the APIs request get a 404 error ... but this is another thing to check. Thanks!!

**Comment by phoet** [comment]
The send_keys methd hangs indefinitively for me when i submit the vin. There is not much in the logs

```
2024/10/07 10:15:15 INFO ECDSA private key generated and saved
2024/10/07 10:15:15 INFO ECDSA public key generated and saved
2024/10/07 10:15:15 DEBU privateKeyFile loaded
2024/10/07 10:15:15 INFO BleControl initialized
2024/10/07 10:15:24 DEBU connecting to vehicle (A)...
2024-10-07T10:15:24+02:00 [debug] Creating new BLE device
2024-10-07T10:15:24+02:00 [debug] Searching for BLE beacon S43172b7a80223604C...
```

Since I try this from my mac, I attached it to this post where it looks like it should work on one.
