### ISSUE TITLE
Add charge_port_door_open

### ISSUE THREAD

**Issue by protree** [wimaha/TeslaBleHttpProxy#36]
Hello, thank you for your great work!
Is it possible to add the function „charge_port_door_open“?  This function should not only open the charge port but also unlocks a charging cable connected to it to plug it out then. Would be really nice to have a smart button next to my tesla that unlocks the charging cable through my home automation system (iobroker) -> http request to TeslaBleHttpProxy!

**Comment by wimaha** [comment]
Hi @protree,

it is easy to add this command to the proxy. Maybe you want to file a PR?

**Comment by protree** [comment]
I don't know Go but I will take a look at it ;)

**Comment by wimaha** [comment]
Done :-)
