### ISSUE TITLE
Can’t open dashboard

### ISSUE THREAD

**Issue by Arturfrain** [wimaha/TeslaBleHttpProxy#42]
Hi, I try to install the BLE proxy on a PI Zero W. I succeeded install with the image followed by dev.
After docker compose up -d
It says 
[+] running 1/0
Container Tesla-ble-http-proxy  Started.

now as in the documentation said I want to browse to http://“my-pizero-ip”:8080/dashboard
But no connection can be established. 
I have no clue what I do wrong. Maybe is it a problem with the pi zero w? Do I need a other Raspberry Pi model? Maybe Pi Zero W is not working due to 32bit ? 
SSH works over WLAN. Only when using a web browser and trying to connect to that dashboard no connection possible.

Any help is appreciated

**Comment by wimaha** [comment]
Can you please restart the container and copy the logs (`docker logs --since 12h tesla-ble-http-proxy`). Thank you!

**Comment by Arturfrain** [comment]
Thank you, I am away from home until Wednesday. I will do that then and post.

**Comment by Arturfrain** [comment]
Hallo, ich habe nun auf einem PI4 unter 64bit intstalliert. Es funktioniert alles.  Ich habe evcc mit dem Sponsortoken un dem Tesla Template laufen. Die Http Proxy arbeitet sehr schnell. Man verwendet ja nach wie vor die Tesla Fleet API zur Abfrage des SOC. Gibt es dadurch eventuelle Einschränkungen bei der Steuerung im Modus PV ?
Danke für das tolle Programm !!
